name: "CI"

on:
  pull_request:
  push:
    branches:
      - "master"
  schedule:
    - cron: "42 3 * * *"
  workflow_dispatch:

jobs:
  phpunit:
    name: "PHPUnit"
    runs-on: "ubuntu-20.04"

    strategy:
      matrix:
        php-version:
          - "5.4"
          - "5.5"
          - "5.6"
          - "7.0"
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
        phpunit-versions:
          - "latest"
        dependencies:
          - "highest"
        include:
          - dependencies: "lowest"
            php-version: "5.4"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "none"
          ini-values: "zend.assertions=1"
          tools: phpunit:${{ matrix.phpunit-versions }}

      - name: "PHP < 7.0"
        if: "${{ matrix.php-versions }} < 7.0"
        run: composer require --dev --with-all-dependencies --no-install phpunit/phpunit 4.8

      - name: "PHP 7.0"
        if: "${{ matrix.php-versions }} == 7.0"
        run: composer require --dev --with-all-dependencies --no-install phpunit/phpunit 6.0

      - name: "PHP 7.4"
        if: "${{ matrix.php-versions }} == 7.4"
        run: composer require --dev --with-all-dependencies --no-install phpunit/phpunit 8.0

      - name: "PHP >8.0"
        if: "${{ matrix.php-versions }} >= 8.0"
        run: composer require --dev --with-all-dependencies --no-install phpunit/phpunit

      - name: "Install dependencies"
      - run: composer update

      - name: "Run PHPUnit"
        run: "vendor/bin/phpunit"
